package com.study.springboot.enumeration.error;


import lombok.Getter;

@Getter
public enum StatusCode {

    ADMIN_NO_PERMISSION("ENP00"),
    ADMIN_LOGIN("AD01"),
    ADMIN_PW_INVALID("EAL01"),
    USER_NOT_FOUND("ENF01"),
    USER_NO_PERMISSION("ENP00"),
    USER_REG_SUCCESS("UR00"),
    USER_LOGIN("UR01"),
    USER_LOGIN_PW_INVALID("EUL01"),
    USER_REG_FAILED("EUR00"),
    USER_REG_ID_EXISTS("EUR01"),



    PRODUCT_REMOVE_SUCCESS("PR00"),
    PRODUCT_CHECK_SUCCESS("PR01"),
    PRODUCT_REMOVE_FAIL("EPR00"),
    PRODUCT_NOT_FOUND("EPR01"),
    PRODUCT_LIST_NOT_FOUND("EPR02"),
    PRODUCT_CODE_MISMATCH("EPR03"),
    PRODUCT_EDIT_SUCCESS("PE00"),
    PRODUCT_EDIT_FAILED("EPE00"),


    ORDER_LIST_FOUND_SUCCESS("OLF00"),
    ORDER_LIST_DELETE_SUCCESS("OLD00"),
    ORDER_LIST_NOT_FOUND("EOLD01"),
    ORDER_LIST_UPDATE_SUCCESS("OLU00"),
    ORDER_ITEM_UPDATE_SUCCESS("OI00"),
    ORDER_ITEM_NOT_FOUND("EOI00"),
    ORDER_ITEM_ORDER_LIST_MISMATCH("EOI01"),
    ORDER_FOUND_SUCCESS("OF00"),
    ORDER_REVENUE_LIST_FOUND_SUCCESS("ORL00"),
    ORDER_COUNT_LIST_FOUND_SUCCESS("OCL00"),


    USER_DELETE_SUCCESS("UD00"),
    USER_UPDATE_SUCCESS("UU00"),
    USER_FOUND_SUCCESS("UF00"),
    USER_LIST_NOT_FOUND("EUF00"),
    USER_LIST_FOUND_SUCCESS("UF01"),
    ORDER_LIST_CREATE_SUCCESS("OL00"),
    ORDER_LIST_CREATE_FAILED("EOL00"),
    ORDER_LIST_PAYMENT_SUCCESS("OL01"),
    ORDER_LIST_PAYMENT_FAILED("EOL01"),
    ORDER_LIST_SUCCESS("OL02"),

    ;


    private String value;
    StatusCode(String value){
        this.value = value;
    }
}
